service: serverless-boilerplate

frameworkVersion: '3'

plugins:
  - serverless-offline-ssm
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-tracing
  - serverless-layers

provider:
  name: aws
  runtime: nodejs18.x
  stage: local
  region: us-west-2
  timeout: 30
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm
          Resource: '*'
        - Effect: Allow
          Action: s3
          Resource: '*'
  environment:
    ALLOWED_ORIGINS: ${ssm:/${opt:stage, self:provider.stage}/lambda/COMMON/ALLOWED_ORIGINS}

custom:
  serverless-offline-ssm:
    stages:
      - dev
    ssm:
      '/dev/lambda/COMMON/ALLOWED_ORIGINS': '*'