service: serverless-boilerplate

frameworkVersion: '3'

plugins:
  - serverless-offline-ssm
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-tracing
  - serverless-layers

provider:
  name: aws
  runtime: nodejs18.x
  stage: local
  region: us-west-2
  timeout: 30
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ssm
          Resource: '*'
        - Effect: Allow
          Action: s3
          Resource: '*'
  environment:
    ALLOWED_ORIGINS: ${ssm:/${opt:stage, self:provider.stage}/lambda/COMMON/ALLOWED_ORIGINS}

custom:
  serverless-offline-ssm:
    stages:
      - dev
    ssm:
      '/dev/lambda/COMMON/ALLOWED_ORIGINS': '*'

functions:
  common:
    handler: src/handler.run
    description: Routing event to common APIs
    tracing: true
    architecture: arm64
    events:
      - httpApi:
          path: /v1/common/{proxy+}
          method: any
  todo:
    handler: src/handler.run
    description: Routing event to todo APIs
    tracing: true
    architecture: arm64
    events:
      - httpApi:
          path: /v1/todo/{proxy+}
          method: any

resources:
  Resources:
    StatusTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: application-status-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 1
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todo-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: task
            AttributeType: S
          - AttributeName: status
            AttributeType: BOOL
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: status
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true